version: '3.7'

services:
  mancala-game:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
  mongodb:
    image: mongo:5.0.1-focal
    container_name: "mancala-mongo"
    ports:
      - "27017:27017"
